# Generated by Django 2.1.3 on 2018-11-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_word', models.CharField(max_length=100)),
                ('eng_word', models.CharField(max_length=100)),
            ],
        ),
    ]
